# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19_SkH88q8OrhV-1xgR6kYeOoJeQNNBwC
"""

!pip install streamlit

!pip install cryptocompare

# Commented out IPython magic to ensure Python compatibility.
# %%writefile crypto_streamlit.py
# import streamlit as st
# import cryptocompare
# 
# st.title("Crypto Price Viewer")
# 
# # Get the list of available cryptocurrencies
# cryptos = cryptocompare.get_coin_list(format=True)
# crypto_choices = st.multiselect("Select cryptocurrencies", list(cryptos.keys()))
# 
# if crypto_choices:
#     for crypto in crypto_choices:
#         # Get the current price of the selected cryptocurrencies
#         price = cryptocompare.get_price(crypto, currency='USD')
#         st.write(f"Current price of {crypto}: {price['USD']}")

!streamlit run crypto_streamlit.py